name: Book CI
on:
  push:
    branches: # build any changes to main
      - main
  pull_request: # build all PRs
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-java@3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build book
        run: npm run setup
